### ISSUE TITLE
text cut off when right aligned

### ISSUE THREAD

**Issue by darenr** [Jasonette/JASONETTE-Android#111]
reproducible test case:

https://jasonbase.com/things/Kq4r.json

**Comment by gliechtenstein** [comment]
From your markup I see the style looks like this:

```
     "styles": {
        "banner": {
          "width": "100%",
          "padding": "15",
          "size": "20",
          "corner_radius": "3",
          "background": "#000000",
          "color": "#ffffff",
          "align": "right"
        }
      },
```

The cutoff goes away when you get rid of the width, because then it automatically resizes to fit the width.

What's happening here is you've set the width of the textfield as 100%, and unlike iOS where it automatically constrains itself so that it doesn't go out of bounds, on Android it does. That's why the 100% width actually results in a full 100% of the device width, and since we also have a padding of 15 to the left, it pushes it that much outside of the window.

For now you can just get rid of the width line and it will work, but I do think this needs to be consistent, so have created an issue here https://github.com/Jasonette/documentation/issues/58

**Comment by darenr** [comment]
great thanks, I'll remove that and give it a try.
