### ISSUE TITLE
[Feature] Allow to center title

### ISSUE THREAD

**Issue by realitix** [Jasonette/JASONETTE-Android#124]
Currently, the title in `body.header` can't be centered, it should be.

In the `JasonViewActivity`, we should add a `TextView` for the title instead of relying on `toolbar.setTitle`.

**Comment by realitix** [comment]
I have to check the IOs behavior

**Comment by realitix** [comment]
IOs center the title so there is a inconsistency

**Comment by gliechtenstein** [comment]
I actually kept it this way because i thought this was the way the title is shown natively, but I do agree it's inconsistent.

Are there a lot of android apps where the header is center aligned? In terms of consistency it would be great to have it center aligned, but I also don't want the UI to feel alien because that's not what most Android users are used to. (I use iPhone as my main phone and Android for only certain tasks and development so I'm not a good sample)

**Comment by realitix** [comment]
I did the pull request.

Spotify use centered title. Personally, I find it way better like that. I understand your point of view about app that feels alien, it's a good point. We have to check on major APP to see the behavior on android.

First of the list:

- Spotify

**Comment by realitix** [comment]
@gliechtenstein After testing several major applications, indeed on Android, the title is not usually centered. Spotify seems to be an exception.

Do you think we could add an option to the json object to force it on android ? I personally want to center my title and I can't currently.

I wait for your opinion about it. :sunglasses:
