### ISSUE TITLE
V8 crashes sometimes

### ISSUE THREAD

**Issue by realitix** [Jasonette/JASONETTE-Android#137]
In my App, I sometimes get this error :

```
07-12 14:10:49.334 7006-7041/com.jasonette E/AndroidRuntime: FATAL EXCEPTION: Thread-5
                                                             Process: com.jasonette, PID: 7006
                                                             java.lang.Error: Invalid V8 thread access.
                                                                 at com.eclipsesource.v8.V8Locker.acquire(V8Locker.java:34)
                                                                 at com.jasonette.seed.Core.JasonParser$1.run(JasonParser.java:59)
                                                                 at java.lang.Thread.run(Thread.java:764)
```

It crashes the app.
It looks like V8 should not be used with multi-thread (https://github.com/eclipsesource/J2V8/issues/33)

**Comment by gliechtenstein** [comment]
Could you share when this happens?

I am aware that this happens when using the [$timer](http://docs.jasonette.com/actions/#timer) action because the threading is complicated in that case. It's a special case. But other than that I am not aware of crashing so if you can share when this happens that would be helpful.

As for the multithreading issue, if you read through the entire thread you linked to, there actually is a solution and it's been fixed. And that's the approach the current version of Jasonette is using. (I had to go through that exact thread multiple times to figure out the current solution :D) 

I can't remember from top of my head what drove me to implement this inside the thread but I do remember there was a reason why it was implemented. I am pretty sure it will crash a lot of existing apps if we get rid of the thread. I will try to remember what the reason was and share it if I can recall.

Anyway, I think it would be much safer and efficient to figure out these edge cases (like the $timer) and fix them instead of getting rid of multithreading, so i would appreciate it if you could share the crashing apps/examples.

**Comment by realitix** [comment]
Thanks for your answer @gliechtenstein.
I don't use `$timer` in my app. I'm going to package the APP and send it to you because this error occurs with local file (I didn't try with http json).

**Comment by gliechtenstein** [comment]
@realitix sounds good!

**Comment by maks** [comment]
This could be to the lock not being released in JasonParser.java when an exception is thrown, see: https://github.com/Jasonette/JASONETTE-Android/blob/develop/app/src/main/java/com/jasonette/seed/Core/JasonParser.java#L99

If that is the case, @realitix you should be seeing in your logcat the output from: 
https://github.com/Jasonette/JASONETTE-Android/blob/develop/app/src/main/java/com/jasonette/seed/Core/JasonParser.java#L103

somewhere **before** you see the exception you included in this issue report.

@realitix if you are able to reproduce this error, hopefully you can quickly prove/disprove my theory.

**Comment by realitix** [comment]
Here the example APP. Just copy all files into assets/file directory. And make your app point to `file://main.json`.
[jasonette_example.zip](https://github.com/Jasonette/JASONETTE-Android/files/1148085/jasonette_example.zip)

Like you can see, I use a lot of mixin, so it may be the cause of the problem

**Comment by gliechtenstein** [comment]
Thanks for the example @realitix 
I took a look and it looks like it's because the local json read is happening on the main thread. Please try out this branch and see if this works https://github.com/Jasonette/JASONETTE-Android/pull/142

**Comment by realitix** [comment]
Fixed
