### ISSUE TITLE
Thread issue with loading

### ISSUE THREAD

**Issue by realitix** [Jasonette/JASONETTE-Android#143]
Hello @gliechtenstein,

I LOVE thread! I just found a very annoying concurrency problem with the loading page.
[Here](https://github.com/Jasonette/JASONETTE-Android/blob/develop/app/src/main/java/com/jasonette/seed/Core/JasonViewActivity.java#L271), we fetch the loading gif and just after [Here](https://github.com/Jasonette/JASONETTE-Android/blob/develop/app/src/main/java/com/jasonette/seed/Core/JasonViewActivity.java#L275), we fetch the real page. If it was not multi-threaded, it would work well. But each of theses methods are run in a thread. Sometime (often), my page locks on the loading animation. After digging, I think I know why.
If the main page is loaded faster than the loading page, when the loading page is ready, it will call `view.build` and replace the page content with the loading page forever.

2 solutions:
- Wait for the loading fetch to finish before run the main fetch (but slow!)
- Add a condition (in JasonModel) that checks if view is built, if it's built, we don't call `view.build` for the loading fetch. 

I wait for your call @gliechtenstein

**Comment by maks** [comment]
@realitix I think you are right in that there is a race condition here, but looking at the code, it seems only fetch_http() happens on a background thread, while fetch_local happens on the main thread (which is actually a bug in itself).
But fixing this is using your suggestion 2 is not as easy as it sounds as you can see that the code path of fetching and displaying the loading content is generic, so you would either need to treat fetching & displaying the loading code as a specific separate case (not ideal) or want a means to specify an ordering to content being fetched.
That might actually point to a nicer solution to this: using an intent service for handling all network requests or using one of the [new lifecycle aware classes](https://medium.com/google-developers/lifecycle-aware-data-loading-with-android-architecture-components-f95484159de4) as the current implementation is also   not going to cope with config changes like orientation changes during a http request.

**Comment by realitix** [comment]
Hi @maks. Thanks for your answer.
@gliechtenstein recently added fetch_local in a background thread. Just update your develop branch and you will see it.
I agree with you that the solution 2 needs to keep trace of the loading call of `fetch_local` and thus loose its generic signature.

**Comment by maks** [comment]
@realitix sorry I have the current develop branch here but dont see where fetch_local is running on a background thread? It calls JasonHelper.read_json() which does all its work on the current thread?
Actually looking at that code, I think there is a bug in there as its using is.available() to determine the size of the file but that's only going to work with files smaller than whatever internal buffer the class libraries inputstream implementation uses...Though it does mean that essentially the read call never blocks but it looks rather dicey to me...

And sorry I did **not** mean that fetch_local should stop being generic. I mean that the current implementation has more problems than the issue you have raised here, so my suggestion would be to rework both network and local fetches into a separate service or use another lifecycle-aware approach such as the one in the article I linked too, as the current code will **not** cope with Android configuration changes when a network request is in-flight.

**Comment by realitix** [comment]
Indeed it's not in develop branch, it's in this pull request https://github.com/Jasonette/JASONETTE-Android/pull/142
You point very good points that we should discuss with @gliechtenstein.

**Comment by maks** [comment]
Thanks yes I forgot about that PR.
Yes this definitely does need more discussion 
@gliechtenstein when you get a chance hopefully you can comment further about this and my above concerns with the fetch_local code.

**Comment by gliechtenstein** [comment]
Thanks for bringing this up! I'm glad that you guys found this out. 

To be honest, I initially designed Jasonette to be online-only, and only decided to go all out on offline features recently because I see a huge potential in offline (and also decentralized) apps. And I probably made some mistakes here and there pushing out the offline features as a result.

This is especially true with `loading.json` and `error.json`. I should have taken more care supporting these two but I just got excited with the offline features and just added these seemingly innocent features without thinking about all the complexity they're introducing. I've been struggling to handle all the edge cases introduced with these recently.

Which reminds me, there was a similar problem on iOS. And I solved it with an approach similar to what @realitix suggested as the second solution:

> Add a condition (in JasonModel) that checks if view is built, if it's built, we don't call view.build for the loading fetch.

A similar approach on Android would look something like the following (I haven't tested this so there may still be bugs):

```
    public void fetch_local(final String url){
        final JasonViewActivity context = this.view;
        try {
            Runnable r = new Runnable()
            {
                @Override
                public void run()
                {
                    jason = (JSONObject)JasonHelper.read_json(url, context);
                    refs = new JSONObject();

                    // loaded is the non-loading.json URL that's currently loaded
                    if (url.equalsIgnoreCase("file://loading.json")) {
                        if (loaded) {
                            // the real URL already loaded, so need to ignore and NOT build.
                            return;
                        } else {
                            // the real URL not yet loaded, so go on to resolve_and_build
                        }
                    } else {
                        // set "loaded" to true and go on to resolve_and_build
                        loaded = true;
                    }

                    resolve_and_build(jason.toString());
                }
            };
            Thread t = new Thread(r);
            t.start();

        } catch (Exception e) {
            Log.d("Warning", e.getStackTrace()[0].getMethodName() + " : " + e.toString());
        }
    }
```

Maybe we could try fixing the immediate problem at hand this way for now, and then think about the other problems separately?



## But a special treatment just for loading.json doesn't feel right!

Just to be clear, I do get @maks point that it doesn't feel right, and it would be nice if we could come up with a cleaner approach to this. 

But one thing to remember is this `file://loading.json` **is** indeed a very special case so handling this file in a special manner is not necessarily the worst case scenario. 

## About orientation change

Currently we handle orientation change in a very tedious manner, we store them in SharedPreference everytime the orientation changes and retrieve them onResume. 

So I agree that using the `ViewModel` from the Architecture Components (this is what you were referring to right?) feels much cleaner and more effective.

But also I feel like this may potentially be a huge brain surgery, because if we try to switch this out, it wouldn't be as simple as just making `JasonModel` inherit `ViewModel`, but also have to update all the current logic for handling view-model state binding.

## Summary

I guess my point is, I do think at some point it would be nice if we can use more sophisticated binding method such as the Architecture Components, but maybe overhauling the entire app just for dealing with this `loading.json` situation right now is a bit too much. The way I see it is: 

1. We have an immediate problem that we need to fix
2. We can probably solve this with a special treatment for `loading.json`.
3. I think this special treatment--while doesn't feel perfect--is an ok solution for now, since it IS a special case.
4. But @maks's point is still valid and I do think it would be nice to use the Architecture Components approach (I'm guessing you're referring to the ViewModel class) at some point because it can act as a nice way to transition to a more reactive approach in the future (Currently all view updates are carried out as a full page refresh, but I think eventually we want to support partial rendering)
5. That said, I am concerned that overhauling the model-view relationship right now is like opening a whole can of worms and not sure if it's worth it.

What do you think? Let me know if I missed something. Also please feel free to correct me if above code doesn't look like it will work. I can't test with Android studio at the moment so I just wrote up the code without testing..

**Comment by maks** [comment]
@gliechtenstein Thinking it over, I think you have a good point, putting in a temp fix for the specific issue is a good idea as there are other more pressing things to fix right now and refactoring to use a diff http/file IO mechanism would be a big change, though perhaps not as big as it might first appear.

**BUT** I think it needs to be done sooner rather than later. What I meant about orientation changes is that in Android, that causes the Activity to be destroyed and then recreated. Best case if you have a network request(s) in-flight they will all be thrown out and done again. Worst case, if you are holding onto a reference to the Activity context you **will** have a memory leak. I've noticed you do pass around the activity context in a few spots, I haven't had a chance yet to look to see if that will be causing a mem leak but its quite possible, this is the most common source of mem leaks (and other issues) in Android apps.

I think though I've polluted this issue with out of scope issues too much already, so I'll move this into a new issue to track.

**Comment by realitix** [comment]
@gliechtenstein I agree: hot fix for now and refactoring next.

**Comment by gliechtenstein** [comment]
Turns out this is not a simple matter of view rendering, it involves action call chains.

For example, we can't treat a view as "loaded" until all actions on `$show` or `$load` have completed. I tried to make this work but for some reason it kept crashing.

So I ended up just disabling `loading.json` for local JSON URLs altogether. https://github.com/Jasonette/JASONETTE-Android/pull/142/commits/32fe533a93b752f0a264f682a3c4eb05d36d7659

This is the simplest solution for now (assuming people will want to use loading.json when their home url is from a remote JSON. Loading a local file for loading another local file seems a bit redundant anyway)

I'm gonna merge it but @realitix please confirm this fixes the problem too.

**Comment by gliechtenstein** [comment]
@realitix yes I agree. let's revisit this as soon as we have some more time on hand.

**Comment by realitix** [comment]
I'm testing it. I will tell you tomorrow if it's ok and then we'll close this issue.

**Comment by realitix** [comment]
It works. I close it.
