### ISSUE TITLE
How can I customise $util.alert?

### ISSUE THREAD

**Issue by sergiogomes** [Jasonette/JASONETTE-Android#237]
Is there a way I can display only a Ok button in the alert?
And if I wanted to pass a variable with the text I want to be displayed through options, How could I do that?

**Comment by Malavos** [comment]
I'm quite interested in this as well!

**Comment by Malavos** [comment]
Anyone? +1!

**Comment by mcken2ja** [comment]
This can be achieved by added a bit of logic into the JasonUtilAction file. In mine, I added two options attributes called success and cancel that would represent the text I wanted to display instead of the normal defaults.   

What you would have to do for example is set up two variables to default as the values:
**String success = "OK";**
**String cancel = "Cancel";**

Next, in the part around the options object setup an IF to see if you passed in overrides: 
**if (options.has("success")){
    success = options.get("success").toString();
}
if (options.has("cancel")){
    cancel = options.get("cancel").toString();
}**
Finally make sure you set the value on the display object.

builder.setPositiveButton(**success**,
    new DialogInterface.OnClickListener() {
        public void onClick(DialogInterface dialog,
                            int which) {
            try {
    ...


Do that also for the cancel button.
