### ISSUE TITLE
when using transition: replace, rotation takes app to previous view

### ISSUE THREAD

**Issue by cpg** [Jasonette/JASONETTE-Android#5]
use this url (page One), then click on Jump, to take you to page Two, then rotate the device:

https://jasonbase.com/things/zYJ

**Comment by gliechtenstein** [comment]
I know what the problem is, and will make sure to fix this.

That said, I would like to advise against using replace transition as much as possible. Replace transition was added for exceptional cases where you can't possibly find another way of dealing with the problem at hand.

The reason why I say this is because unlike websites, on mobile apps people expect each view to serve a single purpose. Which means, when you want to open a detail view from a master view, people expect it to open up in a completely new view (on Android via Intent, and on iOS via either modal or push segue).

So when people see this type of replace transition happening between views they get the impression that the app doesn't feel native--it feels like transition between web pages when you click a link.

In most cases you should be able to come up with a better UX than replace, and replace should be the last resort if you really can't come up with a better solution.

**Comment by gliechtenstein** [comment]
This should be fixed with https://github.com/Jasonette/JASONETTE-Android/commit/bd67a71a3f9da81a981da6ab7a87ca550a1d099a

Please try

**Comment by cpg** [comment]
Works and no extra calls are done in rotations. Great job.

I disagree on several fronts, however.

The lecture about the use case really clashes with the disparate comments about Jasonette being primarily a REST client and not doing too many things locally. Things are already quite clumsy as they are, with calls from on view to another going blank and slow with even moderate network latency (this is probably one of the main issues in real life usage).

There are already lots of things one has to work-around to make things work to something that feels usable, let alone to make something smoothly interactive feel close to native. It's quite infuriating to be doing demos and things stalling to a blank screen for one to several seconds (even using data and templates). My apps all use https, so maybe http2 might help with latency issues and overall speed things up.

Saying that "on mobile apps people expect each view to serve a single purpose" is meaningless and event preposterous (people don't know even what a view is). Most native apps I use have no way to go back to some "top level page" unless one "logs out", and in some cases, unless one uninstalls. They are called "modalities" and they have existed in software of all kinds for decades.

Further, _putting it on me_ to not be able to "come up with a better UX" from the limited palette we have (fantastic platform as it may be), is kind of insulting.

That said, if footer tabs are fixed to be used dynamically without introducing instability, I will explore removing the replace if it makes things feel more native, even though I think this is the proper choice here.

Recapping, I had to use `replace` for mainly two reasons:

1) to go from an "external" page to a logged-in page inside the app. Different "modality" in the app.
2) because the footer tabs apparently have to be there from the very first page (which does not work well, UI-wise), and using replace makes their behavior somewhat stable in the inside of the app
