### ISSUE TITLE
Random Force close Horizontal / few Images combination

### ISSUE THREAD

**Issue by carstengrimm** [Jasonette/JASONETTE-Android#91]
Having random force close on android app when accessing json views with a few "image components which are loaded in a mixture of horizontal and vertical items. While this force close will happen about 2/10 times accessing the view. 

master as well as development branch, on multiple android devices

**Comment by gliechtenstein** [comment]
This should be fixed with https://github.com/Jasonette/JASONETTE-Android/commit/f94b27face351ebc094377446977b32da4260a4d

Basically the problem was happening when you have bottom tab bar AND use a map component, because map component was attaching touch event handler to the main view. It was never cleaned up when we switch to another tab, so when you switch away to another tab and try to do something, that touch event handler would trigger and it would crash. 

Fixed it by detaching all touch handlers whenever the view switches. Please try it out and let me know if that fixed it!

**Comment by carstengrimm** [comment]
seems good now.
