### ISSUE TITLE
Mario Android demo API 22 and 23, not working

### ISSUE THREAD

**Issue by j2l** [Jasonette/JASONETTE-Android#95]
Testing Mario from https://raw.githubusercontent.com/Jasonette/Jasonpedia/gh-pages/view/layer/dynamic.json on my Android 5.1.1 phone (API 22) and emulator (API 22 and 23).
I see Mario and can click buttons, but mario is not draggable, rotatable or resizable.
Win10, Android Studio 2.3

Edit: Tested on Mac, it works. So only Android issue.

**Comment by gliechtenstein** [comment]
Yes you are right, the draggable/rotatble/resizable are not yet implemented on Android.

I just created an issue here just so that the title is more specific, please follow along: https://github.com/Jasonette/JASONETTE-Android/issues/98

Maybe we should take that out of the example until it's implemented on the android side as well, so as to not confuse users. Sorry about the confusion!
