### ISSUE TITLE
[Helpful] Here are my snippets for Atom IDE

### ISSUE THREAD

**Issue by j2l** [Jasonette/JASONETTE-Android#96]
OK, While I was reading Jasonette documentation, I wrote a quick snippets list for [Atom](https://atom.io/):
[https://github.com/j2l/My-Atom-snippets](https://github.com/j2l/My-Atom-snippets)
Put them in you {user}/.atom folder.
It surely miss things and have errors, keep in mind this is a first draft.

If you'd like to contribute/correct it, feel free but don't expect immediate action from me. I wanted to contribute my way since I'm not a great coder.
May be Jasonette issue is not the right place, I don't know where to place it.

Hope it helps develop Jasonette community!

**Comment by realitix** [comment]
Thanks @j2l for this nice contribution.
Actually, this is not the good place for this. I recommend you to open a pull request to https://github.com/Jasonette/documentation and to put your contribution in this file: https://github.com/Jasonette/documentation/blob/master/docs/convention.md

Then you will have feedbacks.
Can you close this issue in order to minimize the number of opened issues.

Regards,

**Comment by j2l** [comment]
I can't continue tracking bugs.
